#!/bin/bash

echo -e "\nSynchronisation du temps\n"
hwclock --systohc --utc
ntpdate -qu 0.be.pool.ntp.org > /dev/null
timedatectl set-timezone Europe/Brussels
timedatectl set-ntp true

systemctl restart ntpd

hwclock --systohc --utc
ntpdate -qu 0.be.pool.ntp.org
timedatectl set-timezone Europe/Brussels
timedatectl set-ntp true
sleep 1

echo ""
ntptime
echo ""
timedatectl
echo ""
