#!/bin/bash

USER=toto

# create Jail Directory
function create_directory {

	echo -e "création des répertoire\n"
	mkdir -pv /home/jail/{home,etc/skel}

	echo -e "Modification des droits\n"
	chown -v root:root /home/jail
	chmod -v go-w /home/jail
	
	# cp -avr /etc/skel/ /home/jail/etc/skel/
	cp -ar /etc/skel/ /home/jail/etc/skel/
}

function create_user {

	# create User
	echo -e "Create User"
	useradd -m -g users -G sshusers --home /home/jail/home/toto -s /usr/bin/zsh 
toto
	yes "toto" | passwd toto
	usermod --home /home/toto toto

	echo -e "create /etc/passwd File"
	cat /etc/passwd | grep '^toto:' > /home/jail/etc/passwd
}

function temp_dir {
	mkdir -pv /{etc/jail/toto,var/jail/toto/{cache/{key,pkg},lib}}
	chown -v toto:users /var/jail/toto/cache/key
	cp -avr /etc/pacman.conf /etc/jail/toto/pacman.conf
	chown -Rv toto:sshusers /var/jail/toto/cache/key
	cp -avr /etc/pacman.conf /etc/jail/toto/pacman.conf
}

function clean_dir {
	rm -rfv /etc/jail/toto/
	rm -rfv /var/jail/toto/
}

function install_dir {
	pacman --dbpath /var/jail/toto/lib         \
		   --root /home/jail                   \
		   --cachedir /var/jail/toto/cache/pkg \
		   --config /etc/jail/toto/pacman.conf \
		   --logfile /var/jail/toto/pacman.log \
		   -Sy bash nano which tar less grep zsh coreutils 
zsh-autosuggestions \
		            zsh-completions zshdb zsh-history-substring-search 
zsh-lovers \
		            zsh-syntax-highlighting zsh-theme-powerlevel9k 
powerline-fonts \
		            awesome-terminal-fonts acpi
}

function mount_dir {

	echo -e "Creation des Noeux\n"
	mknod -m 600 /home/jail/dev/console c 5 1
	mknod -m 666 /home/jail/dev/null c 1 3

	echo -e "Montage des Noeux\n"
	mount -v --bind /dev /home/jail/dev
	
	mount -vt devpts devpts /home/jail/dev/pts -o gid=5,mode=620
	mount -vt proc proc /home/jail/proc
	mount -vt sysfs sysfs /home/jail/sys
	mount -vt tmpfs tmpfs /home/jail/run
	
	if [ -h /home/jail/dev/shm ]; then
		mkdir -pv /home/jail/$(readlink /home/jail/dev/shm)
	fi
}

function main {
	create_directory
	create_user
	temp_dir
	install_dir
	clean_dir
	mount_dir
}	

main
